apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: rancher/scheduler:env
        ports:
        - containerPort: 9090
        env:
        - name: DBHOST
          value: db-service

---

apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: default
spec:
  selector:
    app: scheduler
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
