version: 2
jobs:

  test_build:
    working_directory: ~/testcircleci
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run:
          name: Install Maven
          command: 'sudo apt-get install -y maven'
      - run:
          name: Test
          command: 'mvn test'
      - run:
          name: Build web app
          command: 'mvn clean install -Pweb; mvn eclipse:clean eclipse:eclipse -Pweb'
      - run:
          name: Build scheduler app
          command: 'mvn clean install -Pscheduler; mvn eclipse:clean eclipse:eclipse -Pscheduler'
      - store_artifacts:
          path: endpoints-0.1.jar
      - store_artifacts:
          path: scheduler-0.1.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_build:
          filters:
            branches:
              only: master
